grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30091

kube-state-metrics:
  image:
    registry: docker.io
    repository: wsnbwz/kube-state-metrics
    tag: "v2.9.2"

prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: true
      image:
        registry: docker.io
        repository: sdedu/kube-webhook-certgen
        tag: v20230407 #v20221220-controller-v1.5.1-58-g787ea74b6

prometheus:
  ## Configuration for Prometheus service
  ##
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    retention: 2h # 只保留2小时的数据
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: mylocalsc1
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    remoteWrite:
    - url: http://victoriametrics1-victoria-metrics-cluster-vminsert.default:8480/insert/616/prometheus/api/v1/write
      # name: clusteraa1
    enableRemoteWriteReceiver: true
    enableFeatures:
    - remote-write-receiver