grafana:
  enabled: false

kube-state-metrics:
  image:
    registry: docker.io
    repository: wsnbwz/kube-state-metrics
    tag: "v2.9.2"

prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: true
      image:
        registry: docker.io
        repository: sdedu/kube-webhook-certgen
        tag: v20230407 #v20221220-controller-v1.5.1-58-g787ea74b6

prometheus:
  ## Configuration for Prometheus service
  ##
  service:
    type: NodePort
    nodePort: 30090

