---
# Source: kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus1-kube-prometheu-thanos-discovery
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-thanos-discovery
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus1
    app.kubernetes.io/version: "47.3.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-47.3.0
    release: "prometheus1"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus1-kube-prometheu-prometheus
