
# 定义prome-alert-trans的Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prome-alert-trans
  name: prome-alert-trans
spec:
  serviceName: "prome-alert-trans"
  selector:
    matchLabels:
      app: prome-alert-trans
  template:
    metadata:
      labels:
        app: prome-alert-trans
    spec:
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/hfbbg4/prometheus-alert:v0.0.2 # hefabao/prometheus-alert:v0.0.2 # 官方 feiyu563/prometheus-alert:latest #像是是放了个自身的广告
        name: prome-alert-trans
        env:
        - name: PA_LOGIN_USER
          value: "prometheusalertmm1"
        - name: PA_LOGIN_PASSWORD
          value: "prometheusalertmm1"
        - name: PA_TITLE
          value: "PrometheusAlert"
        - name: PA_OPEN_FEISHU
          value: "1"
        - name: PA_OPEN_DINGDING
          value: "1"
        - name: PA_OPEN_WEIXIN
          value: "1"
        # - name: PA_FSURL
        #   value: "https://open.feishu.cn/open-apis/bot/v2/hook/08409dc4-6ef3-4893-9648-bb72e024dc56"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: alertvolume
          mountPath: /app/db
  volumeClaimTemplates:
  - metadata:
      name: alertvolume
    spec:
      storageClassName: mylocalsc1
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      # volumes:
      # - name: alertvolume
      #   # 使用pvc
      #   hostPath:
      #     path: /mnt/disks/prome-alert
      #     type: DirectoryOrCreate
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: myalert
      #           operator: In
      #           values:
      #           - a


---
#定义prome-alert-trans的Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-prome-alert-trans
  name: svc-prome-alert-trans
  
spec:
  selector:
    app: prome-alert-trans
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30388
