---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  prometheus1-kube-prometheu-admission-patch
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded   
  labels:
    app: kube-prometheus-stack-admission-patch    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus1
    app.kubernetes.io/version: "47.3.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-47.3.0
    release: "prometheus1"
    heritage: "Helm"
spec:
  template:
    metadata:
      name:  prometheus1-kube-prometheu-admission-patch
      labels:
        app: kube-prometheus-stack-admission-patch        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: prometheus1
        app.kubernetes.io/version: "47.3.0"
        app.kubernetes.io/part-of: kube-prometheus-stack
        chart: kube-prometheus-stack-47.3.0
        release: "prometheus1"
        heritage: "Helm"
    spec:
      containers:
        - name: patch
          image: docker.io/sdedu/kube-webhook-certgen:v20230407
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name=prometheus1-kube-prometheu-admission
            - --namespace=monitoring
            - --secret-name=prometheus1-kube-prometheu-admission
            - --patch-failure-policy=
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: prometheus1-kube-prometheu-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
