"global":
  "resolve_timeout": "5m"
"inhibit_rules":
- "equal":
  - "alertname" 
  "source_matchers":
  - "severity = critical"
  "target_matchers":
  - "severity =~ warning|info"
- "equal":
  - "alertname"
  - "instance"
  "source_matchers":
  - "severity = warning"
  "target_matchers":
  - "severity = info"
"receivers":
- "name": "Default"
  webhook_configs:
  - url: http://192.168.113.249:30388/prometheusalert?type=dd&tpl=dd2&ddurl=https://oapi.dingtalk.com/robot/send?access_token=8ab8ebb239d957c7aaba03c8619392f48dc6836fa7d85cc166c3135d6fa98537
    send_resolved: true

  # - url: http://192.168.113.249:30388/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=8ab8ebb239d957c7aaba03c8619392f48dc6836fa7d85cc166c3135d6fa98537
  #   send_resolved: true

- "name": "webhook-dingding"
  webhook_configs:
  - url: http://192.168.113.249:30388/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=8ab8ebb239d957c7aaba03c8619392f48dc6836fa7d85cc166c3135d6fa98537
    send_resolved: true

- "name": "Watchdog"
- "name": "Critical"
- "name": "null"
"route":
  "group_by": ["namespace","alertname"]
  "group_interval": "1m" # 测试用,1m进行重新发状态
  "group_wait": "30s"
  "receiver": "Default"
  "repeat_interval": "1m" # 测试用,3m进行重新发状态
  "routes":
  - "matchers":
    - "namespace = monitoring"
    "receiver": "webhook-dingding"
  # - "matchers":
  #   - "alertname = InfoInhibitor"
  #   "receiver": "null"
  # - "matchers":
  #   - "severity = critical"
  #   "receiver": "Critical"
