---
# Source: thanos/templates/compactor/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thanos1-compactor
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.11.2
    app.kubernetes.io/instance: thanos1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: compactor
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: mylocalsc1
  resources:
    requests:
      storage: "8Gi"
