---
# Source: thanos/templates/ruler/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos1-ruler
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.11.2
    app.kubernetes.io/instance: thanos1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ruler
  annotations:
automountServiceAccountToken: true
