## **572tusj**   配置AlertManager示例：设置匹配PrometheusAlert（对接钉钉和微信）
apiVersion: v1
kind: Secret
metadata:
  labels:
    release: prometheus1
  name: alertmanager-prometheus1-kube-prometheu-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
    "inhibit_rules":
    - "equal":
      - "alertname" 
      "source_matchers":
      - "severity = critical"
      "target_matchers":
      - "severity =~ warning|info"
    - "equal":
      - "alertname"
      - "instance"
      "source_matchers":
      - "severity = warning"
      "target_matchers":
      - "severity = info"
    "receivers":
    - "name": "Default"
      - url: http://svc-prome-alert-trans.default/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://open.feishu.cn/open-apis/bot/v2/hook/73dcd779-f0d3-4f73-9dbf-7b1a3341df2f
        send_resolved: true
    - "name": "DFeishu"
      webhook_configs:
      - url: http://svc-prome-alert-trans.default/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://open.feishu.cn/open-apis/bot/v2/hook/73dcd779-f0d3-4f73-9dbf-7b1a3341df2f
        send_resolved: true
    - "name": "Watchdog"
    - "name": "Critical"
    - "name": "null"
    "route":
      "group_by":
      - "instance"
      - "job"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "1m" # 测试用,3m进行重新发状态
      "routes":
      - "matchers":
        - "alertname = node-eng-count"
        "receiver": "DFeishu"
      # - "matchers":
      #   - "alertname = InfoInhibitor"
      #   "receiver": "null"
      # - "matchers":
      #   - "severity = critical"
      #   "receiver": "Critical"
type: Opaque
