"global":
  "resolve_timeout": "5m"
"inhibit_rules":
- "equal":
  - "alertname" 
  "source_matchers":
  - "severity = critical"
  "target_matchers":
  - "severity =~ warning|info"
- "equal":
  - "alertname"
  - "instance"
  "source_matchers":
  - "severity = warning"
  "target_matchers":
  - "severity = info"
"receivers":
- "name": "Default"
  - url: http://192.168.0.66:30388/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=8ab8ebb239d957c7aaba03c8619392f48dc6836fa7d85cc166c3135d6fa98537
    send_resolved: true
- "name": "DFeishu"
  webhook_configs:
  - url: http://192.168.0.66:30388/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=8ab8ebb239d957c7aaba03c8619392f48dc6836fa7d85cc166c3135d6fa98537
    send_resolved: true
- "name": "Watchdog"
- "name": "Critical"
- "name": "null"
"route":
  "group_by":
  - "instance"
  - "job"
  "group_interval": "5m"
  "group_wait": "30s"
  "receiver": "Default"
  "repeat_interval": "1m" # 测试用,3m进行重新发状态
  "routes":
  - "matchers":
    - "alertname = node-eng-count"
    "receiver": "DFeishu"