apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-prometheues
  name: node-prometheues
  namespace: cce-monitor
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 9090-9090
    nodePort: 31769
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: server
  sessionAffinity: None
  type: NodePort