apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus1
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-08-14T05:50:14Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 47.3.0
    chart: kube-prometheus-stack-47.3.0
    heritage: Helm
    release: prometheus1
  name: prometheus1-kube-prometheu-prometheus
  namespace: monitoring
  resourceVersion: "380091"
  uid: 39cdddb2-80ba-477e-972b-2e1318ea5e60
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: prometheus1-kube-prometheu-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://prometheus1-kube-prometheu-prometheus.monitoring:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.45.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prometheus1
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prometheus1
  replicas: 1
  retention: 2h
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: prometheus1
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: prometheus1
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: prometheus1-kube-prometheu-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prometheus1
  shards: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: mylocalsc1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v2.45.0
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-08-14T05:50:40Z"
    observedGeneration: 1
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-14T05:50:40Z"
    observedGeneration: 1
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
