---
# Source: thanos/templates/query/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos1-query
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.11.2
    app.kubernetes.io/instance: thanos1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query
    
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30453
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: thanos1
    app.kubernetes.io/component: query
