---
# Source: thanos/templates/query/service-grpc.yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos1-query-grpc
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.11.2
    app.kubernetes.io/instance: thanos1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
      nodePort: null
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: thanos1
    app.kubernetes.io/component: query
